%YAML:1.0

# HDL-64E
lego_loam.laser.num_vertical_scans: 64 
lego_loam.laser.num_horizontal_scans: 1800 
lego_loam.laser.ground_scan_index: 50 
lego_loam.laser.vertical_angle_bottom: -24.9          # degrees
lego_loam.laser.vertical_angle_top: 2              # degrees
lego_loam.laser.sensor_mount_angle: 0               # degrees
lego_loam.laser.scan_period: 0.1                    # seconds

lego_loam.imageProjection.segment_valid_point_num: 5
lego_loam.imageProjection.segment_valid_line_num: 3
lego_loam.imageProjection.segment_theta: 60.0                      # decrese this value may improve accuracy

lego_loam.featureAssociation.edge_threshold: 0.1
lego_loam.featureAssociation.surf_threshold: 0.1
lego_loam.featureAssociation.nearest_feature_search_distance: 5

lego_loam.mapping.enable_loop_closure: false
lego_loam.mapping.mapping_frequency_divider: 5

lego_loam.mapping.surrounding_keyframe_search_radius: 50.0   # key frame that is within n meters from current pose will be
# considered for scan-to-map optimization (when loop closure disabled)
lego_loam.mapping.surrounding_keyframe_search_num: 50        # submap size (when loop closure enabled)

lego_loam.mapping.history_keyframe_search_radius: 7.0        # key frame that is within n meters from current pose will be considerd for loop closure
lego_loam.mapping.istory_keyframe_search_num: 25            # 2n+1 number of history key frames will be fused into a submap for loop closure
lego_loam.mapping.history_keyframe_fitness_score: 0.3        # the smaller the better alignment

lego_loam.mapping.global_map_visualization_search_radius: 500.0 # key frames with in n meters will be visualized
